### PR TITLE
Make the render work with older f#

### PR DESCRIPTION
**Pull request by davidtme**
When using `FSharp.Compiler.Tools` you do not have access to:

* opening of static classes
* `member _.` - this is throwing an error but I can't find the documentation when this was added - quite hard to search for

 this just add `GeneratedCodeUtils` to the functions and replace `_.` with `this.`

### CODE REVIEW

**Comment by cmeeren** [comment]
There is no opening of static classes in generated code. I don't think this change is needed.

Instead of `this.`, you can use `__.` (double underscore). That works for older F#, and still signifies that it should be ignored.

**Comment by cmeeren** [comment]
> I can't find the documentation when this was added - quite hard to search for

Not sure what you're after here.

**Comment by davidtme** [comment]
@cmeeren sorry, I think the _ problem was thrown me off and making me thinking it was a static class

**Comment by cmeeren** [comment]
Released in v0.2.6.

**Pull request merged**
